version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5040:5040"
    environment:
      - MONGO_URI=mongodb://mongo:27017/workoutdb
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "5041:5041"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
